### ISSUE TITLE
Generated response is not detected by common clients like dig or avahi-resolve-host-name

### ISSUE THREAD

**Issue by giddel** [bnielsen1965/mdns-server#10]
My generated response object looks like:
```
{
  id: 0,
  type: 'response',
  flags: 0,
  flag_qr: true,
  opcode: 'QUERY',
  flag_aa: false,
  flag_tc: false,
  flag_rd: false,
  flag_ra: false,
  flag_z: false,
  flag_ad: false,
  flag_cd: false,
  rcode: 'NOERROR',
  questions: [ { name: 'EM-Test.local', type: 'A', class: 'IN' } ],
  answers: [
    {
      name: 'EM-Test.local',
      type: 'A',
      ttl: 3600,
      class: 'IN',
      flush: false,
      data: '192.168.1.106'
    }
  ],
  authorities: [],
  additionals: []
}
```

... which seems not to be a valid response.

A working response from a real device looks like:
```
{
  id: 0,
  type: 'response',
  flags: 1024,
  flag_qr: true,
  opcode: 'QUERY',
  flag_aa: true,
  flag_tc: false,
  flag_rd: false,
  flag_ra: false,
  flag_z: false,
  flag_ad: false,
  flag_cd: false,
  rcode: 'NOERROR',
  questions: [ { name: 'EVX01-200005854.local', type: 'A', class: 'IN' } ],
  answers: [
    {
      name: 'EVX01-200005854.local',
      type: 'A',
      ttl: 3600,
      class: 'IN',
      flush: false,
      data: '192.168.1.149'
    }
  ],
  authorities: [],
  additionals: []
}
```
... which is detected as valid response.

The only differences I can see is in 'flags' and 'flags_aa'. But I found no way to set these flags by code.
What I'm missing here?

**Comment by bnielsen1965** [comment]
The [dns-packet](https://www.npmjs.com/package/dns-packet) module is used to construct the dns packet from the packet object that you pass to the respond() method.

From the [dns-packet](https://github.com/mafintosh/dns-packet/blob/master/index.js#L1649) module the AA flag value is 1024.

If you add a "flags" field to your respond packet then you can set the Authoritative Answer flag...
```javascript
...

mydns.respond({
  flags: 1024,
  answers: [
    {
      name: 'EM-Test.local',
      type: 'A',
      ttl: 3600,
      class: 'IN',
      flush: false,
      data: '192.168.1.106'
    }
  ]
});

...
```

To make the code more readable you could require the dns-packet module and use the AUTHORITATIVE_ANSWER constant...

```javascript

const DNSPacket = requir("dns-packet");

...

mydns.respond({
  flags: DNSPacket.AUTHORITATIVE_ANSWER,
  answers: [
    {
      name: 'EM-Test.local',
      type: 'A',
      ttl: 3600,
      class: 'IN',
      flush: false,
      data: '192.168.1.106'
    }
  ]
});

...
```

**Comment by giddel** [comment]
Thanks a lot for this info, I didn't found this hint during visiting the code. 
My responses are now looking fine :-) Theoretically.  Unfortunately they are still not detected as valid responses by scanner-tools like avahi-utils. But this may be another problem ...
