### ISSUE TITLE
Error bind EADDRNOTAVAIL during mDNS discovery

### ISSUE THREAD

**Issue by AlCalzone** [bnielsen1965/mdns-server#5]
I'm using mdns-server in my library. A user is getting the following error during the mdns discovery (https://github.com/AlCalzone/node-tradfri-client/issues/328):
```
Error: bind EADDRNOTAVAIL fd6e:b0a:4804:1:c52:2e6e:664:2942%en0 
at dgram.js:334:20 
at processTicksAndRejections (internal/process/task_queues.js:82:21) (node:11198) 
```
At a first glance I could not see why this error is being raised instead of ignoring the network interface. Any ideas?

**Comment by bnielsen1965** [comment]
The EADDRNOTAVAIL was not properly captured in 1.0.6, try testing the latest version 1.0.8 to see if it solves the issue.

Let me know if you see any issues come up with 1.0.8.

**Comment by AlCalzone** [comment]
Thanks for the quick response. I'll let you know if that works.

**Comment by AlCalzone** [comment]
I haven't heard anything, so I guess this works now. If not, I'll reopen.
