### ISSUE TITLE
No available interfaces

### ISSUE THREAD

**Issue by akshay20jha** [bnielsen1965/mdns-server#6]
hello dear , i am having an issue while using this package i am just getting error of 'no available interfaces' in react native project i am using my physical android device for testing i just want ip address from "xxxx.local" url so can you please help

**Comment by bnielsen1965** [comment]
The module may not work in a react native project due to incompatible dependencies.

However, there is a fork specifically for react native, try this module...

https://github.com/netbeast/react-native-mdns-server

That fork has some changes that add react native compatible dependencies.

**Comment by akshay20jha** [comment]
I thought both the modules are same but now I think I got it  please correct me if I am wrong  do i need to update index.js file according to the provided library....... because installation process and npm command for both the libraries are same

**Comment by bnielsen1965** [comment]
It looks like the react module is not in the npm database, you will need to install from github.
I am not familiar with react-native programming but maybe if you try this...

1) Remove the current mdns-server module...

> npm remove mdns-server


2) Install the react-native-mdns-server module

> npm install https://github.com/netbeast/react-native-mdns-server


3) Update your code to use the react module, I.E.

```javascript
const mdns = require('react-native-mdns-server')({
  reuseAddr: true,
  loopback: true,
  noInit: true
});
```

**Comment by akshay20jha** [comment]
dear thanks fro your reply I tried this way also but the problem in packages are not forming a proper bundle due to this it ends up with hell lot of errors .

**Comment by akshay20jha** [comment]
It would be very helpful if author tells how to install it properly

**Comment by bnielsen1965** [comment]
@akshay20jha  there isn't much more I can do to help with the react issue. I'm going to close this issue and recommend that you engage the react community to see if they can resolve the issue.
